### ISSUE TITLE
Block sizes in 'How to take part'

### ISSUE THREAD

**Issue by dannolloth** [Rafnuss/johnstottbirdingday#4]
Can all the block sizes be the same size? Blocks 1-4
Makes sense for them to be all the size of the largest which is H=431px
Then centre (or middle) align all the text within that box

**Comment by Rafnuss** [comment]
Not exactly sure what you mean by block. If you mean the sections, they should all be 700px height. 
![image](https://user-images.githubusercontent.com/7571260/113295179-25e15080-92f8-11eb-945b-54d92cac52df.png)

The text is middle aligned for all expect the man because of how we use the collapse to go under the image.

Am I understanding it wrongly?

**Comment by dannolloth** [comment]
Sorry, I mean the blocks within how to take part

<img width="1540" alt="image" src="https://user-images.githubusercontent.com/81353383/113295615-57561e00-92f0-11eb-8273-1ae676cef63d.png">
 I wonder if they can all be the same size height and then text in the middle of them.

**Comment by Rafnuss** [comment]
Feel free to close with issue if the update solved it
